### PR TITLE
Local SIC error plots

### PR DESCRIPTION
**Pull request by ots22**
Implements #104 

Adds an 'icenet_plot_sic_error_local' command

### TODO

- [x] Column headings that work better with pandas.read_csv
- [x] Add comment with key to probe/obs_kind
- [x] Emit plots
- [x] Some refactoring (a lot of shared code between this and sic_error)
- [ ] Allow specifying locations as lat/lon
- [ ] Output map

### CODE REVIEW

**Comment by ots22** [comment]
Example with two probes.  Currently this works as follows:

```
$ icenet_plot_sic_error_local \
      north results/predict/demo_test_north.nc '2014-03-01' \
      -p 180,180 \
      -p 200,200 \
      -o sic_error_local_demo.csv

$ head sic_error_local_demo.csv
probe,0,0,0,1,1,1
obs_kind,0,1,2,0,1,2
time,,,,,,
2014-03-02,0.98863393,0.98,0.008633912,0.99100626,0.99,0.0010062456
2014-03-03,0.9886668,0.98,0.008666754,0.9910748,0.99,0.001074791
2014-03-04,0.9885136,0.97,0.01851356,0.9907544,0.98,0.010754406
2014-03-05,0.98871845,0.97,0.018718421,0.9909184,0.97,0.02091837
2014-03-06,0.9888393,0.97,0.0188393,0.99059737,0.97,0.020597339
2014-03-07,0.98919827,0.98,0.009198248,0.9907657,0.98,0.010765672
2014-03-08,0.9896468,0.99,-0.00035321712,0.9909438,1.0,-0.0090562105
```

**Comment by ots22** [comment]
This is probably ready for review now @JimCircadian (a couple of unticked boxes, but these could also be on a separate PR).

I've rebased this one now - the main conflict was with the updated CLI argument handling. What do you think of this approach? It's all on a recent commit, so easy to switch back if you prefer the other way.

The plot output is now to a multi-page pdf, but easy to do other things.  I avoided Seaborn but noticed we've added that as a dependency and means a FacetGrid (one subplot per location) becomes a convenient option as well.  The basic functionality is there, so depends on how configurable it needs to be for this release.

**Comment by JimCircadian** [comment]
Hi @ots22, thanks so much for putting this together. I'm totally happy with basic functionality with room for additional bits and bobs to go in later, no worries. @rchan26 was using seaborn so it seemed reasonable to add that as it's a relatively simple and low impact / high gain dependency. I'll give this a review and resolve the conflicts this morning sometime 😉

**Comment by JimCircadian** [comment]
@ots22 there are a few issues with the merge, as `compute_binary_accuracy` seems to have disappeared and the call to `forecast_plot_args` hasn't been adapted / changed in `leadtime_avg_plots`. If you're happy I'm going to deal with these?

I feel it'll be easier to double check the force push from the rebase hasn't removed any important features when I merge into the upstream release branch from my fork.

**Comment by ots22** [comment]
Ah sorry about that, there were several conflicts which I had to fix manually so might have botched things.  I can make a quick pass now to fix these things if that would be helpful before you have a look?

**Comment by ots22** [comment]
👀 #128

**Comment by ots22** [comment]
Oh yes, It looks like it was just #112 getting merged after I'd already rebased.  #128 looks like it's fixed things though so I'll close this one.

**Pull request closed without merging**
