### PR TITLE
Plotting leadtime averaged metrics

### PR DESCRIPTION
**Pull request by rchan26**
Working towards #95 and #93 to port over leadtime averaged metrics.

- [x] Create functions that compute binary accuracy and SIE (i.e. split up plotting and computing the metric, as useful to compute the metric and use elsewhere)
- [x] Create function which returns the computed metric as a pandas dataframe with columns (initialisation date, leadtime, metric)
- [x] Create functions to compute leadtime averaged metrics
- [x] Create functions to plot leadtime averaged metrics
  - [x] Averaged over all forecasts available
  - [x] Averaged after grouping by month or day
- [x] Create command line interface for producing plots
- [x] Docstrings for new functions
- [x] add option to save and load the dataframe storing the metrics for the forecasts (at each initialisation date and each leadtime) to avoid recomputing them

To do:
- [x] fix the y-axis on heatmap plots (months are not always lining up to the actual initialisation dates. when averaging over month, the values are between 1 and 12, but when averaging over days, the values on the axis are between 1 and 365)

Potential future tasks / issues:
- speed up / optimising computation of metrics dataframe
- add option in CLI to run a forecast over a period at some regularity (e.g. daily, monthly) rather than passing in a forecast file
- if pass in a `data_path` which is successful in loading in precomputed metrics, the forecast file should be optional
```
from icenet.plotting.forecast import plot_metrics_leadtime_avg
forecast_file = "/users/rychan/jambyr-icenet/pipeline/results/predict/demo_test_north.nc"
masks = Masks(north=True)
plot_metrics_leadtime_avg(metric="binacc",
                          masks=masks,
                          hemisphere="north",
                          forecast_file=forecast_file,
                          emcwf=False,
                          average_over="day",
                          output_path=None)
```
creates
binacc_no_comp

whilst 
```
plot_metrics_leadtime_avg(metric="binacc",
                          masks=masks,
                          hemisphere="north",
                          forecast_file=forecast_file,
                          emcwf=True,
                          average_over="day",
                          output_path=None)
```
creates
binacc_comp

Note there's less forecasts to average over when comparing because need to line up the initialisation dates available for SEAS.

Currently need to pass in the forecast file, but maybe will implement ability to create forecasts too later by allowing the user to specify a time period and the frequency of forecasts

### CODE REVIEW

**Comment by rchan26** [comment]
Adding some heatmap comparison plots where we average over a month or day
```
plot_metrics_leadtime_avg(metric="binacc",
                          masks=masks,
                          hemisphere="north",
                          forecast_file=forecast_file,
                          emcwf=False,
                          output_path=None,
                          average_over="month")
```
binacc_heatmap_month_no_comp

If we compare with SEAS, we again average over fewer forecasts as we need the initialisation dates to line up, but we get a difference in performance:
```
plot_metrics_leadtime_avg(metric="binacc",
                          masks=masks,
                          hemisphere="north",
                          forecast_file=forecast_file,
                          emcwf=True,
                          output_path=None,
                          average_over="day")
```
binacc_heatmap_day_comp

To do:
- [ ] fix the y-axis on these plots
- [ ] allow for saving and retrieving pre-computed metric dataframes

**Comment by rchan26** [comment]
Command line interfaces to produce the above plots in order:
```
!icenet_plot_leadtime_avg north /users/rychan/jambyr-icenet/pipeline/results/predict/demo_test_north.nc \
    -m binacc -dp "demo_test_north_binacc_no_comp.csv" -ao all

!icenet_plot_leadtime_avg north /users/rychan/jambyr-icenet/pipeline/results/predict/demo_test_north.nc \
    -m binacc -dp "demo_test_north_binacc_comp.csv" -ao all -e

!icenet_plot_leadtime_avg north /users/rychan/jambyr-icenet/pipeline/results/predict/demo_test_north.nc \
    -m binacc -dp "demo_test_north_binacc_no_comp.csv" -ao month

!icenet_plot_leadtime_avg north /users/rychan/jambyr-icenet/pipeline/results/predict/demo_test_north.nc \
    -m binacc -dp "demo_test_north_binacc_comp.csv" -ao day
```

There is now ability to save the plots, the code will first try to load in the data (path specified after `-dp` flag), but if not successful, it will compute the metrics dataframe and then save it there. So here, the first two commands creates the metrics dataframes and stores them in `demo_test_north_binacc_no_comp.csv` (metrics for all initialisation dates in the forecast file and has no comparison to SEAS) and `demo_test_north_binacc_comp.csv` (metrics for the initialisation dates in the forecast file which has corresponding SEAS forecasts for comparison) respectively. In the last two commands, the metrics dataframe that are used to make these plots have already been computed, so just loads in the dataframes and is much quicker.

**Comment by rchan26** [comment]
Realised that due to leap years, the `.dayofyear` attribute for `pd.Timestamp` objects would return different days for "2016-03-01" and "2015-03-1" for example, so now we compute day of year after converting the year to non-leap years for consistency.

Also fixed y-axis for the heatmap plots:

```
icenet_plot_leadtime_avg north /users/rychan/jambyr-icenet/pipeline/results/predict/demo_test_north.nc -m binacc -dp "demo_test_north_binacc_no_comp.csv" -ao month
```
binacc_month

```
icenet_plot_leadtime_avg north /users/rychan/jambyr-icenet/pipeline/results/predict/demo_test_north.nc -m binacc -dp "demo_test_north_binacc_no_comp.csv" -ao day
```
binacc_day

```
icenet_plot_leadtime_avg north /users/rychan/jambyr-icenet/pipeline/results/predict/demo_test_north.nc -m binacc -dp "demo_test_north_binacc_comp.csv" -ao day -e
```
binacc_comp_day

**Comment by tom-andersson** [comment]
Fantastic work @rchan26.

Would it be possible to generate heatmaps with *target date* as the y-axis as well, based on that coordinate in the forecast NetCDFs? These will have a lot of missing values if only using a few forecasts to generate them, but if you had densely-initialised forecasts (eg one per day) then you would get a full heatmap without diagonal stripes of missing values.

**Comment by rchan26** [comment]
Thanks @tom-andersson !

That would be really cool - I _think_ it might be possible to do this with some manipulation of the metrics dataframe that this command computes (dataframe has columns `date` (for initialisation date), `dayofyear` (of init date), `month` (of init date), `leadtime` and the metric name). It could be possible to manipulate this to create new columns of `target_date` (init date + leadtime), `target_dayofyear`, `target_month`) and make this plot...

Will investigate next week and see how far I get 😅

**Comment by rchan26** [comment]
@tom-andersson turned out to be pretty straight forward:

```
icenet_plot_leadtime_avg north /users/rychan/jambyr-icenet/pipeline/results/predict/demo_test_north.nc -m binacc -dp "target_demo_test_north_binacc_no_comp.csv" -ao day -td
```

target_binacc_day

I've added a `-target_date_average` or `-td` flag which makes it average over the target date.

A lot of N/A's like you say due to sparse initialisation dates, but imagine could get filled out nicely if forecasts initialised on a much finer temporal scale. The title notes that some of these are averaged over 0 forecasts - maybe should be 1 actually as it's just one value.

**Comment by tom-andersson** [comment]
That's perfect, thank you @rchan26!

Super minor, but I prefer darker colours to indicate poorer performance, so for accuracy it would be nice to revert the colormap with '_r'.

**Comment by JimCircadian** [comment]
@tom-andersson there's an issue to allow specifying of colour maps via the CLI which needs contributing to 😉

**Comment by rchan26** [comment]
@tom-andersson set the colour map to `inferno` now (previously `inferno_r`:

binacc_day_r
target_binacc_day

**Comment by JimCircadian** [comment]
This is lush @rchan26, nice work!!! 🚀

**Pull request merged**
